#include "hal_data.h"
#include <stdio.h>
#include "lsm6dsv16x_reg.h"
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

fsp_err_t err = FSP_SUCCESS;
volatile bool uart_send_complete_flag = false;
void user_uart_callback (uart_callback_args_t * p_args)
{
    if(p_args->event == UART_EVENT_TX_COMPLETE)
    {
        uart_send_complete_flag = true;
    }
}

#ifdef __GNUC__                                 //串口重定向
    #define PUTCHAR_PROTOTYPE int __io_putchar(int ch)
#else
    #define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
#endif


PUTCHAR_PROTOTYPE
{
        err = R_SCI_UART_Write(&g_uart9_ctrl, (uint8_t *)&ch, 1);
        if(FSP_SUCCESS != err) __BKPT();
        while(uart_send_complete_flag == false){}
        uart_send_complete_flag = false;
        return ch;
}

int _write(int fd,char *pBuffer,int size)
{
    for(int i=0;i<size;i++)
    {
        __io_putchar(*pBuffer++);
    }
    return size;
}

/* Callback function */
i2c_master_event_t i2c_event = I2C_MASTER_EVENT_ABORTED;
uint32_t  timeout_ms = 100000;
void sci_i2c_master_callback(i2c_master_callback_args_t *p_args)
{
    i2c_event = I2C_MASTER_EVENT_ABORTED;
    if (NULL != p_args)
    {
        /* capture callback event for validating the i2c transfer event*/
        i2c_event = p_args->event;
    }
}

#define SENSOR_BUS g_i2c2_ctrl

/* Private macro -------------------------------------------------------------*/
#define    BOOT_TIME            10 //ms

/* Private variables ---------------------------------------------------------*/
static uint8_t whoamI;
static uint8_t tx_buffer[1000];

static lsm6dsv16x_interrupt_mode_t irq;
static lsm6dsv16x_tap_detection_t tap;
static lsm6dsv16x_tap_thresholds_t tap_ths;
static lsm6dsv16x_tap_time_windows_t tap_win;

/* Extern variables ----------------------------------------------------------*/
lsm6dsv16x_all_sources_t status;
lsm6dsv16x_pin_int_route_t pin_int;
lsm6dsv16x_reset_t rst;
/* Private functions ---------------------------------------------------------*/
/*
 *   WARNING:
 *   Functions declare in this section are defined at the end of this file
 *   and are strictly related to the hardware platform used.
 *
 */
static int32_t platform_write(void *handle, uint8_t reg, const uint8_t *bufp,
                              uint16_t len);
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,
                             uint16_t len);
static void tx_com( uint8_t *tx_buffer, uint16_t len );
static void platform_delay(uint32_t ms);
static void platform_init(void *handle);

static stmdev_ctx_t dev_ctx;
static uint8_t stap_event_catched = 0;
static uint8_t dtap_event_catched = 0;

bool irq_flag =0;
/* Called from icu_irq_isr */
void external_irq6_callback (external_irq_callback_args_t * p_args)
{
    (void) p_args;
    irq_flag = 1;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    //点亮LED
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_04, BSP_IO_LEVEL_HIGH);

    //LIS2MDL CS2->1
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_02, BSP_IO_LEVEL_HIGH);
    //LSM6DSV16X CS1->1
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_02, BSP_IO_LEVEL_HIGH);

    /* Open the transfer instance with initial configuration. */
    err = R_SCI_UART_Open(&g_uart9_ctrl, &g_uart9_cfg);
    assert(FSP_SUCCESS == err);

    unsigned char buff[]="RA E2STUDIO";
    uint8_t buff_len = strlen(buff);
    err = R_SCI_UART_Write(&g_uart9_ctrl, buff, buff_len);
    if(FSP_SUCCESS != err) __BKPT();
        while(uart_send_complete_flag == false){}
    uart_send_complete_flag = false;

    printf("\nhello world!\r\n");



    /* Initialize the I2C module */
    err = R_SCI_I2C_Open(&g_i2c2_ctrl, &g_i2c2_cfg);
    /* Handle any errors. This function should be defined by the user. */
    assert(FSP_SUCCESS == err);

    fsp_err_t err = R_ICU_ExternalIrqOpen(&g_external_irq6_ctrl, &g_external_irq6_cfg);
    assert(FSP_SUCCESS == err);

    err = R_ICU_ExternalIrqEnable(&g_external_irq6_ctrl);
    assert(FSP_SUCCESS == err);

    /* =========================
     *  LSM6DSV16X 单/双击检测示例
     * ========================= */
    lsm6dsv16x_reset_t rst;
    stmdev_ctx_t dev_ctx;
    /* Initialize mems driver interface */
    dev_ctx.write_reg = platform_write;
    dev_ctx.read_reg = platform_read;
    dev_ctx.mdelay = platform_delay;
    dev_ctx.handle = &SENSOR_BUS;

    /* Init test platform */
//    platform_init(dev_ctx.handle);
    /* ---------- 2. 传感器上电后延时 ---------- */
    platform_delay(BOOT_TIME);

    /* ---------- 3. 读取并校验芯片 ID ---------- */
    lsm6dsv16x_device_id_get(&dev_ctx, &whoamI);
    printf("LSM6DSV16X_ID=0x%x,whoamI=0x%x\n",LSM6DSV16X_ID,whoamI);
    if (whoamI != LSM6DSV16X_ID)
      while (1);

    /* ---------- 4. 恢复默认寄存器配置 ---------- */
    lsm6dsv16x_reset_set(&dev_ctx, LSM6DSV16X_RESTORE_CTRL_REGS);
    do {
      lsm6dsv16x_reset_get(&dev_ctx, &rst);
    } while (rst != LSM6DSV16X_READY);

    /* ---------- 5. 使能 Block Data Update ---------- */
    lsm6dsv16x_block_data_update_set(&dev_ctx, PROPERTY_ENABLE);

    /* ========== 6. Tap / Double-Tap 中断配置 ========== */
    /* 6-1 路由单击 & 双击事件到 INT1 引脚 */
    pin_int.double_tap = PROPERTY_ENABLE;// 使能“双击”事件
    pin_int.single_tap = PROPERTY_ENABLE;// 使能“单击”事件
    lsm6dsv16x_pin_int1_route_set(&dev_ctx, &pin_int);
    // 若想用 INT2，可调用 lsm6dsv16x_pin_int2_route_set(&dev_ctx, &pin_int);
    //lsm6dsv16x_pin_int2_route_set(&dev_ctx, &pin_int);

    /* 6-2 打开功能中断总开关 & 选择脉冲模式 */
    irq.enable = 1;// FUNCTIONS_ENABLE.INTERRUPTS_ENABLE = 1
    irq.lir = 0;// TAP_CFG0.LIR = 0 → 脉冲输出
    lsm6dsv16x_interrupt_enable_set(&dev_ctx, irq);

    /* 6-3 选择参与 Tap 检测的轴（此处仅启用 Z 轴） */
    tap.tap_z_en = 1;
    lsm6dsv16x_tap_detection_set(&dev_ctx, tap);

    /* 6-4 设置 Z 轴阈值（3 LSB ≈ 186 mg @ ±8 g） */
    tap_ths.z = 3;
    lsm6dsv16x_tap_thresholds_set(&dev_ctx, tap_ths);

    /* 6-5 设置时间窗：SHOCK / QUIET / DUR
     *   - SHOCK = 3  → 约 58 ms   （峰值持续窗口）
     *   - QUIET = 3  → 约 29 ms   （第一次敲击后的静默期）
     *   - tap_gap= 7 → 约 500 ms  （双击最大间隔）
     *   公式基于 ODR = 480 Hz
     */
    tap_win.tap_gap = 7;
    tap_win.shock = 3;
    tap_win.quiet = 3;
    lsm6dsv16x_tap_time_windows_set(&dev_ctx, tap_win);

    /* 6-6 同时启用单击 + 双击识别 */
    lsm6dsv16x_tap_mode_set(&dev_ctx, LSM6DSV16X_BOTH_SINGLE_DOUBLE);

    /* ========== 7. 加速度计工作参数 ========== */
    /* 7-1 采样率：480 Hz（官方建议 ≥400 Hz 以保证 Tap 检测精度）*/
    lsm6dsv16x_xl_data_rate_set(&dev_ctx, LSM6DSV16X_ODR_AT_480Hz);
    /* 7-2 量程：±8 g（每 LSB ≈ 62 mg，兼顾灵敏度与范围）*/
    lsm6dsv16x_xl_full_scale_set(&dev_ctx, LSM6DSV16X_8g);

    while (1)
    {
        if (irq_flag)  // 如果中断标志被置位（表示有新的 Tap 事件）
        {
            /* 读取所有中断源状态并清除中断 */
            lsm6dsv16x_all_sources_get(&dev_ctx, &status);
            irq_flag = 0;  // 清除中断标志，防止重复处理同一次中断

            if (status.single_tap) {        // 判断是否捕获到“单击”事件
                stap_event_catched = 1;      // 标记单击事件已捕获
            }
            if (status.double_tap) {        // 判断是否捕获到“双击”事件
                dtap_event_catched = 1;      // 标记双击事件已捕获
            }
        }

        if (stap_event_catched) {          // 如果有单击事件需要处理
            stap_event_catched = 0;        // 清除单击事件标志
            printf("Single TAP\r\n");     // 打印“Single TAP”提示
        }
        if (dtap_event_catched) {          // 如果有双击事件需要处理
            dtap_event_catched = 0;        // 清除双击事件标志
            printf("Double TAP\r\n");     // 打印“Double TAP”提示
        }

        R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);  // 延时 10 ms，避免频繁轮询占用 CPU
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}


/*
 * @brief  Write generic device register (platform dependent)
 *
 * @param  handle    customizable argument. In this examples is used in
 *                   order to select the correct sensor bus handler.
 * @param  reg       register to write
 * @param  bufp      pointer to data to write in register reg
 * @param  len       number of consecutive register to write
 *
 */
static int32_t platform_write(void *handle, uint8_t reg, const uint8_t *bufp,uint16_t len)
{
    // 创建一个足够大的缓冲区来包含寄存器地址和数据
    uint8_t data[len + 1];
    data[0] = reg; // 将寄存器地址放在数据的开始
    memcpy(&data[1], bufp, len); // 复制数据到缓冲区

    err = R_SCI_I2C_Write(&g_i2c2_ctrl, data, len+1, true);
    assert(FSP_SUCCESS == err);
    /* Since there is nothing else to do, block until Callback triggers*/
    //while ((I2C_MASTER_EVENT_TX_COMPLETE != i2c_event) && timeout_ms)
    while ((I2C_MASTER_EVENT_TX_COMPLETE != i2c_event) && timeout_ms>0)
    {
        R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);
        timeout_ms--;
        }
    if (I2C_MASTER_EVENT_ABORTED == i2c_event)
    {
        __BKPT(0);
    }
    /* Read data back from the I2C slave */
    i2c_event = I2C_MASTER_EVENT_ABORTED;
    timeout_ms           = 100000;
    return 0;
}


/*
 * @brief  Read generic device register (platform dependent)
 *
 * @param  handle    customizable argument. In this examples is used in
 *                   order to select the correct sensor bus handler.
 * @param  reg       register to read
 * @param  bufp      pointer to buffer that store the data read
 * @param  len       number of consecutive register to read
 *
 */
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,uint16_t len)
{
    err = R_SCI_I2C_Write(&g_i2c2_ctrl, &reg, 1, true);
    assert(FSP_SUCCESS == err);
    /* Since there is nothing else to do, block until Callback triggers*/
    //while ((I2C_MASTER_EVENT_TX_COMPLETE != i2c_event) && timeout_ms)
    while ((I2C_MASTER_EVENT_TX_COMPLETE != i2c_event) && timeout_ms>0)
    {
        R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);
        timeout_ms--;
        }
    if (I2C_MASTER_EVENT_ABORTED == i2c_event)
    {
        __BKPT(0);
        }
    /* Read data back from the I2C slave */
    i2c_event = I2C_MASTER_EVENT_ABORTED;
    timeout_ms           = 100000;

    /* Read data from I2C slave */
    err = R_SCI_I2C_Read(&g_i2c2_ctrl, bufp, len, false);
    assert(FSP_SUCCESS == err);
    while ((I2C_MASTER_EVENT_RX_COMPLETE != i2c_event) && timeout_ms)
    {
        R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MILLISECONDS);
        timeout_ms--;
    }
    if (I2C_MASTER_EVENT_ABORTED == i2c_event)
    {
        __BKPT(0);
    }

    i2c_event = I2C_MASTER_EVENT_ABORTED;
    timeout_ms           = 100000;
  return 0;
}


/*
 * @brief  platform specific delay (platform dependent)
 *
 * @param  ms        delay in ms
 *
 */
static void platform_delay(uint32_t ms)
{
    R_BSP_SoftwareDelay(ms, BSP_DELAY_UNITS_MILLISECONDS);
}


/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
